{"name": "test_get_pro_intent", "status": "broken", "statusDetails": {"message": "UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 0: invalid continuation byte", "trace": "self = <test_get_intent.TestIntent object at 0x0000020C10F6E860>\n\n    @pytest.mark.api_intention_test\n    @allure.feature(\"测试环境通用意图识别\")\n    def test_get_pro_intent(self):\n        # 意图测试\n        # GetRequests().get_request(\"http://192.168.1.79:8900/intention/v2/skin\", \"GET\", \"skin_intent\",\n        #                           \"intent\\\\dermatology\\\\target.txt\",\n        #                           \"intent\\\\dermatology\\\\dermatology_test_data_3995.csv\", [\"sentence\"], \"label\",\n        #                           \"dermatology_intention_test_result.xls\",\n        #                           \"dermatology_intention_target_test_result.xls\")\n        # GetRequests().get_request(\"http://192.168.1.74:8911/gynaecology_intention/v1\", \"GET\", \"pro_intent\",\n        #                           \"intent\\\\gynaecology\\\\线上target.txt\",\n        #                           \"intent\\\\gynaecology\\\\妇科-总测试数据-线上线下.csv\", [\"sentence\", \"False\", \"gynaecology\"],\n        #                           \"label\",\n        #                           \"gynaecology_intention_test_result.xls\",\n        #                           \"gynaecology_intention_target_test_result.xls\")\n        GetRequests().get_request(\"http://192.168.1.79:8905/intention/v2/infertility\", \"GET\", \"a_intent\",\n                                  \"intent\\\\infertility\\\\test_target.txt\",\n                                  \"intent\\\\infertility\\\\intention_to_test.csv\", [\"sentence\"],\n                                  \"label\",\n                                  \"infertility_intention_test_result.xls\",\n>                                 \"infertility_intention_target_test_result.xls\")\n\napi\\test_get_intent.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\api\\get_requests.py:226: in get_request\n    total_num, accuracy)\n..\\api\\get_requests.py:236: in get_target_result\n    target_list = CommonFunction.get_target(self, target_file)\n..\\commonfunc\\common_function.py:325: in get_target\n    for line in file.readlines():\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <encodings.utf_8.IncrementalDecoder object at 0x0000020C13929F98>\ninput = b'\\xc3\\xe8\\xca\\xf6\\xbe\\xcd\\xd5\\xef\\xca\\xb7\\r\\n\\xc3\\xe8\\xca\\xf6\\xd6\\xa2\\xd7\\xb4\\r\\n\\xc8\\xb7\\xb6\\xa8\\xc1\\xaa\\xcf\\xb5\\xd2...d7\\xc9\\xd1\\xaf\\xd7\\xa1\\xd4\\xba\\r\\n\\xd7\\xc9\\xd1\\xaf\\xd7\\xa2\\xd2\\xe2\\xca\\xc2\\xcf\\xee\\r\\n\\xd7\\xc9\\xd1\\xaf\\xd7\\xa8\\xbc\\xd2'\nfinal = False\n\n    def decode(self, input, final=False):\n        # decode input (taking the buffer into account)\n        data = self.buffer + input\n>       (result, consumed) = self._buffer_decode(data, self.errors, final)\nE       UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 0: invalid continuation byte\n\nE:\\Python3.7.3\\lib\\codecs.py:322: UnicodeDecodeError"}, "start": 1594194946673, "stop": 1594195146366, "uuid": "8acb6f9e-9b7d-459e-90bc-c312cdb08d04", "historyId": "5577602bedd8563b8ebaf88513cfdf02", "testCaseId": "49fe48d551064aad013d744258a73f22", "fullName": "pytest.api.test_get_intent.TestIntent#test_get_pro_intent", "labels": [{"name": "feature", "value": "测试环境通用意图识别"}, {"name": "tag", "value": "api_intention_test"}, {"name": "parentSuite", "value": "pytest.api"}, {"name": "suite", "value": "test_get_intent"}, {"name": "subSuite", "value": "TestIntent"}, {"name": "host", "value": "WIN-OQ20V7UABJF"}, {"name": "thread", "value": "7900-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "pytest.api.test_get_intent"}]}